name: Clang Format
inputs:
  directory:
    description: Directory to Lint
    required: true

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: sudo apt install clang-format-12 # This should be roughly in sync with Arcanist

    - name: clang-format
      working-directory: ${{ inputs.directory }}
      shell: bash
      run: clang-format-12
