name: Setup Website envirionment

runs:
  using: "composite"
  steps:
    # TODO: Update to a supported version when website is moved to the
    # workspace version of yoga-layout
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: 12

    # TODO: the website should be in a yarn workspace with the library, but the
    # current version of gatsby is incompatible with hoisting.
    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile
      working-directory: website
