name: Setup JavaScript envirionment

runs:
  using: "composite"
  steps:
    - name: Install emsdk
      uses: ./.github/actions/install-emsdk

    - name: Install Ninja
      uses: ./.github/actions/install-ninja

    - name: Setup Node environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: yarn install
      shell: bash
      run: yarn install --frozen-lockfile

    - name: yarn cache get
      shell: bash
      run: yarn cache get

    - name: wut
      shell: bash
      run: which yarn

    - name: ls
      shell: bash
      run: ls -l /home/runner/.cache/yarn/v6
