name: Website

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-website

      - name: yarn build
        run: yarn build
        working-directory: website
