name: Apple

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-pods:
    name: Lint Podspecs
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-apple

      - name: pod spec lint
        run: pod spec lint --verbose

  install-sample:
    name: Install YogaKitSample
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-apple

      - name: pod install
        working-directory: ./YogaKit/YogaKitSample
        run: pod install

  clang-format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: clang-format
        uses: ./.github/actions/clang-format
        with:
          directory: ./YogaKit
