name: Android

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build (${{ matrix.mode }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: [Debug, Release]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-android

      - name: Build
        run: ./gradlew assemble${{ matrix.mode }}

  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: google-java-format
        run: npx --yes google-java-format --set-exit-if-changed --dry-run --glob=java/**/*.java
